project:
  type: website
  output-dir: docs

website:
  title: "Nissim Lebovits"
  favicon: "assets/alps_profile_pic.jpeg"
  search: 
    location: navbar
    type: overlay
  page-navigation: true
      
  page-footer:
    center: |
      [Contact Me](mailto:nissimlebovits@proton.me)
    left: |
      Powered by [Quarto](https://quarto.org)
    right: |
      &#169; 2025 Nissim Lebovits
    background: "#f8f9fa"

format:
  html:
    theme: 
      light: cosmo
    css: styles.css
    toc: true
    pagetitle: "{{< meta title >}} | Nissim Lebovits"
    smooth-scroll: true
    code-fold: false
    code-tools: true
    code-copy: true

editor: source




babelquarto:
  languagecodes:
  - name: es
    text: "Espa√±ol"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['es']
title-es: Nissim Lebovits
lang: en
